### ISSUE TITLE
convert project into a local package with pip

### ISSUE THREAD

**Issue by chief-khanman** [coordinated-systems-lab/UrbanAirMobility#10]
using pip convert the project into local package. 

add a setup.py and setup.cfg file.

**Comment by jalane76** [comment]
I suggest using [Poetry](https://python-poetry.org/) as it is very easy to use and does a lot of dependency matching/management for you.  It also sets up virtual environments automatically and integrates well with CI/CD pipelines like GitHub Actions.

Setup.py is pretty old by now and the tools that use it are slowly being phased out.

**Comment by chief-khanman** [comment]
Conda doesnt play well with Poetry, keeping the structure for now.
